name: mc

services:
  infrared:
    image: haveachin/infrared:1.3.4 # V2 currently doesn't support stopping/starting docker containers
    container_name: mc-infrared
    volumes:
      - "./configs:/configs" # Infrared server configs
      - "/var/run/docker.sock:/var/run/docker.sock" # Mount the docker daemon socket file into the container so that Infrared can control docker from within the container.
    ports:
      - "25565:25565"
    restart: unless-stopped

  latest:
    image: itzg/minecraft-server
    container_name: mc-latest
    environment:
      TYPE: "PAPER"
      VERSION: "LATEST"
      EULA: "TRUE"
      MOTD: "Dumb server for dumb people"
    volumes:
      - "./data/latest:/data" # Mount server data to local directory (optional)
